### ISSUE TITLE
collapse redundancy

### ISSUE THREAD

**Issue by yannickwurm** [biopet/vepnormalizer#8]
Hello,

thanks for this tool - extremely handy. 

To keep the 1 row per SNP integrity of my VCF I want to use standard mode. 
However, the many commas make subsequent parsing challenging. 

It would be superb if there were a way to intelligently collapse the commas. For example:
 - if all are identical (e.g. for allele frequencies), just report one
 - or report the "worst possible outcome" 

I'm supposing you haven't impleemnted an automated way of doing this?

Thanks
Yannick

**Comment by rhpvorderman** [comment]
Dear Yannick,

Unfortunately the original maintainer of this tool has left our organisation. This tool hasn't been actively maintained since.

What is it exactly that you want the tool to do. Can you provide an example?
Also can you give an example of the problems you get in subsequent parsing? Maybe there is an easier way to solve this problem.

Best regards,
Ruben

**Comment by yannickwurm** [comment]
Dear Ruben,

thank you for the rapid reply. 

For example, in the gnomad frequency column, I was getting 0.4563,0.4563,0.4563,0.4563,0.4563 for a single entry - when I guess there were five transcripts for the gene. 

I was indeed able to resolve this issue, with the following R code

```
  for (column_id in vcf_columns) {
    # eliminate redundancy where it exists
    vcf_tibble$fix[[column_id]]   <- unlist(lapply(strsplit(x = as.character(vcf_tibble$fix[[column_id]]),
                                                            split = ","),
                                                   function(x) { paste(unique(x), collapse=",") }))
  }

```

Thanks again and kind regards,
Yannick

**Comment by rhpvorderman** [comment]
Dear Yannick,

I am happy you were able to solve the issue. Have a nice day!

Best regards,
Ruben
